data:
  file_path: "./data/inputs/chat_parsed/all-messages-endoftext.txt"
ml:
  # Params ref: https://colab.research.google.com/drive/1VLG8e7YSEwypxU-noRNhsv5dW4NfTGce#scrollTo=wmTXWNUygS5E@
  learning_rate: 0.0001 # 1e-4 default
  save_path: "/content/gdrive/MyDrive/collab/data/models_trained/"
  model_size: "124M" # [124M , 355M]
  steps: 1500 # -1 to infinite
  restore_from: "fresh"
  print_every: 1
  sample_every: 300
  save_every: 300
generation:
  prefix: "[others] come stai pistobot dio caro ?"
  temperature: 0.7